# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
      time: "07:00"
      timezone: "Europe/London"
    assignees:
      - "modem7"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/base-fullbuild" # Location of package manifests
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/London"
    assignees:
      - "modem7"

  # Maintain dependencies for PIP
  - package-ecosystem: "pip"
    directory: "/base-fullbuild"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/London"
    assignees:
      - "modem7"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/base-dockercli" # Location of package manifests
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "Europe/London"
    assignees:
      - "modem7"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/base-liveinstall" # Location of package manifests
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "Europe/London"
    assignees:
      - "modem7"