version: "2.4"

services:

  borgmaticrestore:
    container_name: Borg-restore
    volumes:
      - ${VOLUME_TARGET}:/mnt/borg-repository # backup source
      - ${VOLUME_RESTORE}:/RestoreMount # restore target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/ # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg # checksums used for deduplication
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - label:disable
    environment:
      - TZ=$TZ
    devices:
      - /dev/fuse:/dev/fuse
    command: /bin/sh
    image: modem7/borgmatic-docker